### ISSUE TITLE
People Reporting Bugs Should Always Be Anonymous

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [cisagov/cyber.dhs.gov#102]
According to the [Vulnerability Disclosure Policies (Draft) (20-01)](https://cyber.dhs.gov/bod/20-01/) the policy must include "A commitment to not recommend or pursue legal action against anyone for security research activities that the agency concludes represents a good faith effort to follow the policy, and deem that activity authorized".

Anyone who reports a bug to a government agency is most likely doing so with good intentions, regardless of how the bug was found or the initial intent of their actions. While there should be restrictions on what testing is allowed and there should be no guarantee that legal action won't take place, making all bug reports anonymous encourages people to file bug reports. To put it a different way, why would anyone want to help you if there's even a remote threat that you will attempt to harm them?

**Comment by cablej** [comment]
While we should respect an individual's preference to remain anonymous and give them the ability to do so, the intent of this directive is to build relationships with the security researcher community and get to a position of mutual trust. As is industry standard, we should offer legal protection to researchers who make a good faith effort to play by the rules so they are comfortable working with federal agencies. Vulnerability reporting works best when it is not a single isolated action -- by communicating directly, researchers can offer feedback on remediations and test once fixed to confirm that a vulnerability has been effectively patched. Researchers who prefer to stay anonymous may (this is already detailed in the draft), but we all benefit by creating these constructive relationships.

**Comment by zmanion** [comment]
Fully support the goal of making good faith vulnerability research and disclosure common and safe (boring even), and part of this includes building relationships with researchers, which is helped by some degree of engagement and identification (even the consistent use of a handle or alias).

Designing VDPs to preserve anonymity is complicated, costly, and won't do much to change the perception that the government might still identify and take action against researchers. Even a well-meaning VDP could get caught in a web of legal authorities and reporting requirements that could impair the ability to maintain researcher anonymity.

A researcher who wishes to remain anonymous should maintain control and ownership of their anonymity and not rely on a VDP to do so.

**Comment by brittag** [comment]
I support enabling reporters to choose how much they want to disclose about their identities, instead of putting requirements on this. I'm a former federal employee who worked on a team that accepted vulnerability reports from the public, both via email and via HackerOne. These reporters could choose to disclose as much as they wanted about themselves, and various reporters chose to disclose different amounts of information.

I appreciated that I usually had at least a pseudonym and the ability to respond to the person - I could ask the reporter follow-up questions (very important!) and send them thanks (also important!).

Also, our team received a few vulnerability reports from federal employees at other agencies who worked on other teams. This is an important use case to consider. It was easy for those people to report under their real name. If they had to report anonymously, that could cause some strange confusion about whether they were even allowed to report anonymously, because federal employees have lots of ethical requirements and guidance to sort through, which could conflict with anonymous reporting. Easiest to just say who you are!

**Comment by afeld** [comment]
👋 I manage [the program](https://hackerone.com/tts) that @brittag referred to.

Because we use a platform gives ["reputation" points](https://docs.hackerone.com/hackers/reputation.html) for submissions, there's an advantage to not making the submissions anonymously. The platform also supports [disclosure](https://www.hackerone.com/disclosure-guidelines), which gives credit to the reporter, both of which can be non-monetary incentives. In other words, having reports tied to a person (or at least a pseudonym) can be actively positive for everyone involved.
