### ISSUE TITLE
Emailed comment from the Department of Commerce

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/cyber.dhs.gov#116]
> Most federal agencies lack a formal mechanism to receive information from third parties about potential security vulnerabilities on their systems. Many agencies have no defined strategy for handling reports about such issues shared by outside parties. Only a few agencies have clearly stated that those who disclose vulnerabilities in good faith are authorized.

The root cause for agencies having a “lack of a formal mechanism” should also be addressed to encourage transparency and openness. The root cause for not sharing tends to be embarrassment at having the vulnerabilities, which discourages their sharing. However, if more is done to socialize the idea that the presence of vulnerabilities shouldn’t be hidden then that will also help with increasing transparency and sharing.
 
> Agencies should recognize that “a reporter or anyone in possession of vulnerability information can disclose or publish the information at any time”. A key benefit of a vulnerability disclosure policy is to reduce risk to agency infrastructure and the public by incentivizing coordinated disclosure so there is time to fix the vulnerability before it is publicly known.
 
There have been instances in the past when public disclosure of vulnerabilities on Federal systems has led to prosecution. So any “coordinated disclosure” needs to include a mechanism to ensure prosecution will not result from the disclosure.
 
> Within 15 business days after the issuance of this directive, update the following at the .gov registrar: 
>> 1. The security contact field for each .gov domain registered. The email address defined as the security contact must be regularly monitored, and personnel managing it must be capable of triaging unsolicited security reports for the entire domain.
 
A potential risk of publicizing the “.gov registrar” email address in this way opens it up to being a target of malicious actors to create a DoS attack by flooding the site with fake vulnerability info.  
 
> Within 180 calendar days after the issuance of this directive: 3. Publish a vulnerability disclosure policy as a web page in plain text or HTML.
 
Rather than assigning the creation of a policy to agencies to create independently, recommend that CISA lead an effort to coordinate the creation of a policy that federal agencies can use, which takes into account other CISA initiatives, such as CDM. This would allow for a more efficient and successful development and short and long term implementation of the policy.
 
Thank you,
DOC IT Security

**Comment by zmanion** [comment]
>The root cause for not sharing tends to be embarrassment at having the vulnerabilities, which discourages their sharing. However, if more is done to socialize the idea that the presence of vulnerabilities shouldn’t be hidden then that will also help with increasing transparency and sharing.

Agreed. This shift in thinking/perception is one of the keys to operating a VDP that is successful at reducing risk. Realistically, all systems and components have vulnerabilities, we all share this problem. It is perhaps more embarrassing to pretend otherwise or try to hide vulnerabilities (or to "shoot the messenger").

>A potential risk of publicizing the “.gov registrar” email address in this way opens it up to being a target of malicious actors to create a DoS attack by flooding the site with fake vulnerability info.

We operate a public vulnerability reporting email address and I'm aware of many other organizations who do the same. Yes, spam and fake reports are a concern, but experience shows that this is a manageable problem. Of slightly more concern are lengthy, pseudo-accurate, low impact reports that consume more analysis effort than the reports are worth, but this too is manageable. It is generally acceptable to set a reasonably high quality bar for reports.

>Rather than assigning the creation of a policy to agencies to create independently, recommend that CISA lead an effort to coordinate the creation of a policy that federal agencies can use...

Something more/different than this template? https://cyber.dhs.gov/bod/20-01/vdp-template/
