### ISSUE TITLE
Emailed comment from Amélie Koran

### ISSUE THREAD

**Issue by h-m-f-t** [cisagov/cyber.dhs.gov#84]
I would recommend looking at a processing and oversight mechanism that is already in place for agencies - Inspector Generals - that already do audit assessments and have the contact points and relationships to get things patched. IG Empowerment Act provides leverage and doesn’t require more or other legislation or rule making to enforce compliance outside of current authorities. IGs also typically have the knowledge and process in place over the many years of operations to know how to work within agency operations, frameworks and missions to accomplish what is suggested in this BOD. I would seriously suggest re-evaluating the use of bug bounty and bug bounty-like platforms to outsource some of this given the recent Hacker One breach.

This talk was given at BSides NoVA a few years ago that details the challenges and opportunities to this approach.

https://youtu.be/PFFRzrGyyh0

**Comment by chrisspradling1980** [comment]
Amelie:

Recently, there has been many new publications including Heterogeneous
Autonomy while combining technology. In 2017 the Government and White House
proceeded an Vulnerability Equity Process which enabled Business and
Technology to integrate inside a machine learning environment.
Unfortunately, the core subjectivity required a distributed multi agent
link creating a "non-disclosed" sceptical event and is still ongoing.

This process was introduced by almost all major agencies including the
Department of Justice defining the roles and provisional standards
iterating the scope of interest so followers could grasp the real world
translated/hands off initiatives. This role out was a human which the
government never spoke about. Many documents and filings by top government
law makers were sealed or amended regarding secrecy and a predestined
motive. More phenomena occurrences of scientific discovery came as a result
however, the community was weaponized in isolated rural areas to draw
results and consequently, those involved which agreed to enact a
procurement were misled causing chaos to the highest degree.

Ultimately, the consolidation effort by DHS and CIST directives are the
ending to a long effort which returns into a more solidifying carta not to
long from now. Oversight in this field can not be formulated over-the-wire.
All the efforts DHS have responsibilities over are overwhelmingly
disarrayed considering the multiple agency line up directives already. The
usage and practices within the orders of previous Executive orders by
previous administrations contradict and conflict with new ideas because the
limitations of evolving infrastructure capacity to match employee protocol
have become capacitated, reaching its potential with no room to waste on
funding.

What do you do?

Satisfying the evolving growth of human logic tethered with information
systems is extremely high in demand if you are a sensory ad ware developers
or Big Data enthusiast. The law supports definitions under vague
descriptive revised statutes enabling taxation of the machine readable data
derived from human perceivable input instrumenality provides. Neural
networks are not getting the call up it deserves because the instrumenality
retrieves from a wide area distribution host which always suffers damage.
The artificial intelligence suffers also. It's the means to interact inside
the campaign. This will be forgotten only to confine the proceeding to
paper for reference.

True artificial intelligence knows no programmatic inserted behavior. Once
our government realises that automation has always required programmatic
parameters resulting in errors statistically which are an enormous risk to
stabilization and reliance, which is required. There has been minimal
confidence in allowing intelligence as an oversight mitigation utility
coupling human hierarchy of any government. This is trusted to change soon.

Hopefully this little insert brainstormed helps explain the dilemma our
liberty has expounded into.

My funny saying is "Department of Common Sense has located Uncle Sam.
Epsilon stole him, brought him to Shreveport. Now he's Aunt Sammy with a
wig and high hills."

I hope none of our government official do not take offence to my clique.

Chris
